# Adapted from: https://raw.githubusercontent.com/benwilcock/backstage-catalogs/main/ai-asset-catalog.yml
####################################
# COMPONENTS
# A Component represents a model server that's deployed, containing metadata about it
####################################
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: multi-model-service
  annotations:
    backstage.io/techdocs-ref: dir:multi-model-service
  description: 'Ollama-based model service providing models for developer tools.'
  links:
    - url: https://model-service.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: Access
      type: website
      icon: WebAssett
    - url: https://ollama.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: API URL
      type: website
      icon: WebAsset
  tags:
    - genai
    - ibm-granite
    - ollama
    - llm
    - multi-model-service
spec:
  type: model-server
  owner: user:johnmcollier
  lifecycle: production
  providesApis:
    - model-service-api
  dependsOn:
    - resource:ibm-granite-8b-code-instruct
    - resource:meta-llama-31-8b-instruct
    - api:model-service-api
  profile:
    displayName: "Multi Model Service"
---
####################################
# RESOURCES
# A resource (with type `ai-model`) represents an AI model that's deployed on an associated model server
####################################
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ibm-granite-8b-code-instruct
  annotations:
    backstage.io/techdocs-ref: dir:ibm-granite-8b-code-instruct
  description: 'IBM Granite is a decoder-only code model for code generative tasks (e.g. fixing bugs, explaining code, documenting code. Trained with code written in 116 programming languages.'
  links:
    - url: https://model-service.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: Access
      type: website
      icon: WebAssett
    - url: https://ollama.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: API URL
      type: website
      icon: WebAsset
    - url: https://huggingface.co/ibm-granite/granite-8b-code-instruct
      title: Huggingface
      type: website
      icon: WebAsset
    - url: https://www.apache.org/licenses/LICENSE-2.0
      title: Apache-2.0 License
      type: website
      icon: WebAsset
  tags:
    - genai
    - ibm
    - llm
    - "task:text generation"
spec:
  type: llm
  owner: user:johnmcollier
  lifecycle: production
  providesApis:
    - model-service-api
  dependencyOf: 
    - component:multi-model-service
  profile:
    displayName: "IBM Granite Code Model"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: meta-llama-31-8b-instruct
  annotations:
    backstage.io/techdocs-ref: dir:meta-llama-31-8b-instruct
  description: 'Llama 3.1 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety'
  links:
    - url: https://model-service.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: Access
      type: website
      icon: WebAssett
    - url: https://ollama.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: API URL
      type: website
      icon: WebAsset
    - url: https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct
      title: Huggingface
      type: website
      icon: WebAsset
    - url: https://www.apache.org/licenses/LICENSE-2.0
      title: Apache-2.0 License
      type: website
      icon: WebAsset
  tags:
    - genai
    - meta
    - llm
spec:
  type: ai-model
  owner: user:johnmcollier
  lifecycle: production
  providesApis:
    - model-service-api
  dependencyOf: 
    - component:multi-model-service
  profile:
    displayName: "Meta Llama-3.1 8b Model"
######################################
# APIs
# The API object represent the API used by the model server (e.g. OpenAI)
######################################
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: model-service-api
  title: Model Service API
  description: 'The OpenAI-compatible REST API exposed by the Ollama-based multi model service.'
  tags:
    - api
    - openai
    - ollama
  links:
    - url: https://model-service.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/docs
      title: Model Service API Documentation
      type: website
      icon: WebAsset
spec:
  type: openapi
  owner: user:johnmcollier
  lifecycle: production
  dependencyOf: 
    - component:ibm-granite-8b-code-instruct
  definition:
    $text: https://github.com/johnmcollier/rhdh-ai-catalog/blob/main/openapi.json
