site_name: 'Documentation'

nav:
  - Table Of Contents: index.md
  - Model: model.md
  - Usage: code/usage-examples.md
  - Training: training.md
  - Ethics: ethics.md
  - License: license.md

plugins:
  - techdocs-core
