site_name: 'Documentation'

nav:
  - Table Of Contents: index.md
  - Model: model.md
  - Usage: usage-examples.md
  - Training: training.md
  - Ethics: ethics.md
  - License: LICENSE

plugins:
  - techdocs-core
