site_name: 'Documentation'

nav:
  - Table of Contents: index.md
  - Supported Models: models.md
  - Access & Usage Information: code/access.md
  - Usage Disclaimer: usage.md

plugins:
  - techdocs-core
